### PR TITLE
Add my site to blogs list

### PR DESCRIPTION
**Pull request by Aduhelm**
Add cboxes.icu

### CODE REVIEW

**Comment by Aduhelm** [comment]
Thank you for considering my pull request! I have added my blog to the `sites.json` file as requested. Please let me know if there are any issues or further changes needed. Have a great day!

**Comment by artlung** [comment]
Thanks for the submission! It seems like the value ought to be `www.cboxes.icu`? Can you update to that value? Thanks!

**Comment by Aduhelm** [comment]
Hi, I have updated the blog URL to `www.cboxes.icu` as requested. Please let me know if there are any further changes needed. Thanks!

**Review by artlung — APPROVED** [review]

**Comment by artlung** [comment]
Thanks @Aduhelm! Have a great week!

**Comment by Aduhelm** [comment]
Sorry, I missed updating a part. Thank you very much.

**Pull request merged**
